<a href="https://colab.research.google.com/github/MOHAMEDAAKIFASRAR/Implementation-of-Iterative-Policy-Evaluation-for-a-Finite-MDP/blob/main/Policy_evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import gymnasium as gym
import numpy as np

In [2]:
# Create FrozenLake environment
env = gym.make("FrozenLake-v1", map_name="4x4", is_slippery=True)

In [3]:

# Access the unwrapped environment to use the transition model
env = env.unwrapped

In [4]:
# Number of states and actions
n_states = env.observation_space.n
n_actions = env.action_space.n

In [5]:
# Parameters
gamma = 0.99
theta = 1e-8

In [6]:
# Random policy: each action has equal probability
policy = np.ones((n_states, n_actions)) / n_actions

In [7]:
def policy_evaluation(env, policy, gamma=0.99, theta=1e-8):
    """
    Performs iterative policy evaluation using the Bellman expectation equation.

    Returns:
        V : Estimated state-value function
        iteration : Number of iterations used for convergence
    """

    # Initialize value function
    V = np.zeros(env.observation_space.n)

    iteration = 0

    while True:
        delta = 0

        # Update every state
        for s in range(env.observation_space.n):

            v = 0

            # Iterate over all actions
            for a, action_prob in enumerate(policy[s]):

                # Transition probabilities
                for prob, next_state, reward, done in env.P[s][a]:

                    v += action_prob * prob * (
                        reward + gamma * V[next_state] * (not done)
                    )

            delta = max(delta, abs(V[s] - v))
            V[s] = v

        iteration += 1

        # Stop when converged
        if delta < theta:
            break

    return V, iteration

In [11]:
# Run policy evaluation
V, iterations = policy_evaluation(env, policy, gamma, theta)
np.set_printoptions(precision=4, suppress=True, floatmode='fixed')

print("Name: MOHAMED AAKIF ASRAR S")
print("Register Number: 212223240088")
print("Number of iterations:", iterations)
print("\nState-Value Function:")
print(V)

print("\n\nName: MOHAMED AAKIF ASRAR S")
print("Register Number: 212223240088")
print("\nState-Value Function as 4x4 Grid:")
print(np.round(V.reshape(4, 4), 4))

env.close()


Name: MOHAMED AAKIF ASRAR S
Register Number: 212223240088
Number of iterations: 54

State-Value Function:
[0.0124 0.0104 0.0193 0.0095 0.0148 0.0000 0.0389 0.0000 0.0326 0.0843
 0.1378 0.0000 0.0000 0.1703 0.4336 0.0000]


Name: MOHAMED AAKIF ASRAR S
Register Number: 212223240088

State-Value Function as 4x4 Grid:
[[0.0124 0.0104 0.0193 0.0095]
 [0.0148 0.0000 0.0389 0.0000]
 [0.0326 0.0843 0.1378 0.0000]
 [0.0000 0.1703 0.4336 0.0000]]
